### ISSUE TITLE
AP and STA have same WiFi channel.

### ISSUE THREAD

**Issue by uecken** [martin-ger/esp32_nat_router#49]
AP and STA WiFi interfere each other.
Can they avoid using same WiFi channel?

**Comment by martin-ger** [comment]
No, this is by design of the ESP32, as it has only one WiFi transceiver and it must listen all the time at least as AP.

 

Von: kentugi ***@***.*** 
Gesendet: Sonntag, 25. April 2021 06:29
An: martin-ger/esp32_nat_router
Cc: Subscribed
Betreff: [martin-ger/esp32_nat_router] AP and STA have same WiFi channel. (#49)

 

AP and STA WiFi interferes each other.
Can they avoid using same WiFi channel?

**Comment by uecken** [comment]
Thank you for your reply.
